sudo: required
services:
  - docker

before_install:
  - docker build -t lynet2/react-test -f ./client/Dockerfile.dev ./client

script: # all scripts must exit 0 or assume fail
  - docker run lynet2/react-test npm test -- --coverage

after_success:
  - docker build -t lynet2/multi-client ./client
  - docker build -t lynet2/multi-nginx ./nginx
  - docker build -t lynet2/multi-server ./server
  - docker build -t lynet2/multi-worker ./worker

